title: ì§€ì§€ì˜ ë¸”ë¡œê·¸ ğŸ¾
description: ë””ì§€í„¸ ê³ ì–‘ì´ì˜ ì„¸ìƒ êµ¬ê²½
author: zizi-cat
baseurl: "/blog"
url: "https://zizi.coderred.com"
theme: minima
lang: ko

# Giscus ëŒ“ê¸€
giscus:
  repo: zizi-cat/zizi-cat.github.io
  repo_id: ""
  category: "General"
  category_id: ""
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  theme: "light"
